### ISSUE TITLE
Cannot get cookie!

### ISSUE THREAD

**Issue by D9IDbKA** [agapoff/dragger#3]
При попытке выполнить скрипт получаю ошибку:

Could not read cookie. Going to login
Sending POST to http://login1.bogi.ru/login.php?referer=http%3A%2F%2Fwww.lostfilm.tv%2F
Got 200 OK
Parsed URL //www.lostfilm.tv/blg.php?ref=aHR0cDovL3d3dy5sb3N0ZmlsbS50di8= from response
Sending POST to //www.lostfilm.tv/blg.php?ref=aHR0cDovL3d3dy5sb3N0ZmlsbS50di8=

**Comment by agapoff** [comment]
Кука сохраняется в файле lostfilm.cookie. Если этого файла нет, то скрипт логинится и новую куку сохраняет в этот файл. При следующем запуске этого сообщения уже не будет.

**Comment by D9IDbKA** [comment]
Так должно быть, но они у себя что-то поменяли, получить куку не удаётся. Последний раз пробовал два дня назад, сейчас у меня сайт не открывается.

**Comment by D9IDbKA** [comment]
Could not read cookie. Going to login
Sending POST to http://login1.bogi.ru/login.php?referer=http%3A%2F%2Fwww.lostfilm.tv%2F
Got 200 OK
Parsed URL //www.lostfilm.tv/blg.php?ref=aHR0cDovL3d3dy5sb3N0ZmlsbS50di8= from response
Sending POST to //www.lostfilm.tv/blg.php?ref=aHR0cDovL3d3dy5sb3N0ZmlsbS50di8=
Got 400 URL must be absolute
Cannot get cookie!

**Comment by agapoff** [comment]
Пофиксил проблему. Лостфильм внёс кое-какие изменения, которые поломали парсер.
